[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]
#build-std-features = ["compiler-builtins-weak-intrinsics"]

[target.thumbv4t-none-eabi]
runner = "mgba"
rustflags = ["-Clink-arg=-Tlinker_scripts/mono_boot.ld"]

#add rule to flash with cargo flash and use flashgbx like: cargo flash --bin gba-playground

[alias]
flash_gba = "cargo run --runner flashgbx --bin gba-playground"