import enum
import json
from typing import Callable


class FuncType(enum.IntEnum):
    FILTER = 0
    EDIT = 1

class MaxEditor:
    def __init__(self, maxfile: str):
        self.maxfile = maxfile
        with open(maxfile, 'rb') as f:
            data = f.read()
        # crop header until first "{" and footer after last "}"
        json_start = data.find(b'{')
        json_end = data.rfind(b'}') + 1
        self.header = data[:json_start]
        self.footer = data[json_end:]

        self.content = json.loads( data[json_start:json_end].decode('utf-8'))
            # parse_float=lambda s: s + " as float",
            # parse_int=lambda s: s + " as int")

        self.functions: list[tuple[FuncType, Callable]] = []

    def filter(self, filter_func):
        self.functions.append((FuncType.FILTER, filter_func))
        return self

    def edit(self, modify_func):
        self.functions.append((FuncType.EDIT, modify_func))
        return self

    def apply(self):
        boxes = [elem["box"] for elem in self.content["patcher"]["boxes"]]
        for box in boxes:
            for func_type, func in self.functions:
                if func_type == FuncType.FILTER:
                    if not func(box):
                        break
                    continue
                elif func_type == FuncType.EDIT:
                    func(box)
                    continue

        self.functions = []
        return self

    def format_content(self) -> str:
        encoder = MaxJSONEncoder()
        return encoder.encode(self.content)

    def save(self, output_file: str):
        with open(output_file, 'wb') as f:
            f.write(self.header)
            json_content = self.format_content()
            f.write(json_content.encode('utf-8'))
            f.write(self.footer)


def resize_toggle_rect(maxfile: str):
    def resize_rect(box, new_w:int, new_h: int):
        if not 'presentation_rect' in box:
            return False
        new_w = int(new_w)
        new_h = int(new_h)

        rect = box.get('presentation_rect')
        x, y, w, h = rect
        x += (w - new_w) // 2
        y += (h - new_h) // 2
        box['presentation_rect'] = [float(val) for val in [x, y, new_w, new_h]]
        return True


    is_toggle = lambda box: box.get('maxclass') == 'toggle'
    is_autogenerated = lambda box: box.get('id', '').startswith('AUTOGENERATED')
    has_presentation_rect = lambda box: 'presentation_rect' in box
    resize_rect_to_20x20 = lambda box: resize_rect(box, 20, 20)

    editor = MaxEditor(maxfile)
    editor.filter(is_toggle)\
      .filter(is_autogenerated)\
      .filter(has_presentation_rect)\
      .edit(resize_rect_to_20x20)\
      .apply()
    editor.save(maxfile)

def main():
    target_folder = '../../maxGBA'
    # recuresively list all .amxd and maxpat files in the target_folder
    import os
    maxfiles = []
    for root, dirs, files in os.walk(target_folder):
        for file in files:
            if file.endswith('.amxd') or file.endswith('.maxpat'):
                maxfiles.append(os.path.join(root, file))

    print(f"Found {len(maxfiles)} max files to process.")
    for maxfile in maxfiles:
        if "TONE2.amxd" not in maxfile:
            continue

        format_file(maxfile)
        #resize_toggle_rect(maxfile)

def format_file(maxfile: str, output_file: str = None):
    if output_file is None:
        output_file = maxfile

    editor = MaxEditor(maxfile)
    editor.save(output_file)


if __name__ == "__main__":
    main()
