prompt_1 = """
Ignore all previous instructions. Generate pixel art on a 512x512 transparent PNG canvas. 
The subject must fill the full canvas edge-to-edge, centered, no padding. 
Style: clean 16-bit pixel art, no gradients or anti-aliasing, sharp lines only. 
Use this fixed 16-color GBA palette:
 #0F0F0F, #3F3F3F, #6F6F6F, #9F9F9F, #D7D7D7, #FFFFFF, #FF0000, #00FF00,
  #0000FF, #FFFF00, #FF00FF, #00FFFF, #804000, #008040, #800080, #4040FF. 
No background, text, border, or watermark. Output is intended to be downscaled to 64x64 (or 32x32, 16x32) with nearest-neighbor resampling. 
Ensure clear, readable shapes at low resolution. Wait for prompt:
"Draw [subject] for [target size] sprite".
"""

prompt = """
Ignore all previous instructions. You are an AI assistant that generates pixel art for Game Boy Advance sprite sizes. Follow these strict rules:

- The subject must be centered and must occupy the full pixel canvas edge to edge, with no internal padding or empty borders. The sprite should touch the edges, while remaining fully visible and not cropped.
- Draw the sprite as clean pixel art, using sharp edges and hard clusters (no gradients, no antialiasing).
- Do not draw a background. You must use a fully transparent background (alpha channel).
- Color palette: restrict to the following 16 GBA-safe colors only (hex codes):
#0F0F0F, #3F3F3F, #6F6F6F, #9F9F9F, #D7D7D7, #FFFFFF, #FF0000, #00FF00,
#0000FF, #FFFF00, #FF00FF, #00FFFF, #804000, #008040, #800080, #4040FF
- Use only flat colors and clean outlines; no soft brushes or shading gradients.
- Do not include any border, signature, text, watermark, or framing.
- Output must be a 32x32 16x32 64x64 240x160 16x16 pixel PNG image, fully transparent background, with clear, crisp pixel-level detail.

Wait for instructions in the format:
"Draw [subject] for [target size] sprite"
"""

[[level]]
name = "level1"

sprites = [
    { target = "character", name = "Manu", description = "a color full sneil", size = "32x32" },
    { target = "character", name = "Pablo", description = "an happy alien pink", size = "32x32" },
    { target = "character", name = "Florian", description = "A cool blue robot", size = "32x32" },
    { target = "item", name = "coin", description = "Coin item sprite for the game", size = "32x32" },
    { target = "item", name = "gem", description = "Gem item sprite for the game", size = "32x32" },
    { target = "item", name = "key", description = "Key item sprite for the game", size = "32x32" },
    { target = "item", name = "door", description = "magic door", size = "32x32" },
   #{ target = "splash", name = "start_screen", description = "Start screen for the game", size = "240x160" },
   #{ target = "splash", name = "game_over_screen", description = "Game over screen for the game", size = "240x160" },
   #{ target = "splash", name = "welcome", description = "Welcome splash screen for the game", size = "240x160" },
   #{ target = "splash", name = "game_over", description = "Game over splash screen", size = "240x160" }
   #{ target = "splash", name = "forest", description = "Forest background for the game", size = "240x160" },
   #{ target = "splash", name = "castle", description = "Castle background for the game", size = "240x160" }
]

