[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "miditoolkit>=1.0.1",
    "numpy>=2.3.0",
    "opencv-python>=4.11.0.86",
]
